/*
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

package app.gyrolet.mpvrx.network

import android.content.Context
import android.util.AtomicFile
import android.webkit.CookieManager
import okhttp3.Cookie
import okhttp3.CookieJar
import okhttp3.HttpUrl
import okhttp3.HttpUrl.Companion.toHttpUrlOrNull
import java.io.File
import java.nio.charset.StandardCharsets

class AndroidCookieJar : CookieJar {
  companion object {
    private const val PLAYBACK_COOKIE_FILE = "network-cookies.txt"

    fun playbackCookieFile(context: Context): File = File(context.filesDir, PLAYBACK_COOKIE_FILE)
  }

  private val manager: CookieManager? =
    try {
      CookieManager.getInstance()
    } catch (_: Exception) {
      null
    }
  private val responseCookies = linkedMapOf<String, Cookie>()

  override fun saveFromResponse(
    url: HttpUrl,
    cookies: List<Cookie>,
  ) {
    synchronized(responseCookies) {
      removeExpiredCookiesLocked()
      cookies.forEach { cookie -> responseCookies[cookie.storageKey()] = cookie }
    }
    val urlString = url.toString()
    cookies.forEach { cookie ->
      manager?.setCookie(urlString, cookie.toString())
    }
    manager?.flush()
  }

  override fun loadForRequest(url: HttpUrl): List<Cookie> {
    val matchingResponseCookies =
      synchronized(responseCookies) {
        removeExpiredCookiesLocked()
        responseCookies.values.filter { it.matches(url) }
      }
    val webViewCookies =
      manager
        ?.getCookie(url.toString())
        .orEmpty()
        .split(";")
        .mapNotNull { Cookie.parse(url, it.trim()) }

    return (matchingResponseCookies + webViewCookies)
      .associateBy { cookie -> cookie.storageKey() }
      .values
      .toList()
  }

  /**
   * Exports only cookies applicable to [url] for libmpv's Netscape cookie reader. This lets a
   * user-established Android WebView/OkHttp session continue in HLS variant, key, and segment
   * requests without inventing or bypassing challenge cookies.
   */
  fun exportForPlayback(
    url: String,
    destination: File,
  ): Result<Boolean> =
    runCatching {
      val httpUrl = url.toHttpUrlOrNull()
      val cookies = httpUrl?.let(::loadForRequest).orEmpty()
      val atomicFile = AtomicFile(destination)
      val output = atomicFile.startWrite()
      try {
        val payload =
          buildString {
            appendLine("# Netscape HTTP Cookie File")
            appendLine("# Generated by mpvRx for the active playback origin.")
            cookies.forEach { cookie -> appendLine(cookie.toNetscapeLine()) }
          }.toByteArray(StandardCharsets.UTF_8)
        output.write(payload)
        output.flush()
        atomicFile.finishWrite(output)
      } catch (error: Throwable) {
        atomicFile.failWrite(output)
        throw error
      }
      cookies.isNotEmpty()
    }

  private fun removeExpiredCookiesLocked() {
    val now = System.currentTimeMillis()
    responseCookies.entries.removeAll { (_, cookie) -> cookie.expiresAt < now }
  }

  private fun Cookie.storageKey(): String = "$domain\u0000$path\u0000$name"

  private fun Cookie.toNetscapeLine(): String {
    val effectiveDomain = if (httpOnly) "#HttpOnly_$domain" else domain
    val includeSubdomains = if (hostOnly) "FALSE" else "TRUE"
    val secureValue = if (secure) "TRUE" else "FALSE"
    val expires = if (persistent) expiresAt / 1000L else 0L
    return listOf(effectiveDomain, includeSubdomains, path, secureValue, expires, name, value).joinToString("\t")
  }
}
