/*
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

package app.gyrolet.mpvrx.ui.player.ytdlp

import android.content.Context
import android.net.Uri
import android.system.Os
import android.util.Log
import app.gyrolet.mpvrx.network.AndroidCookieJar
import app.gyrolet.mpvrx.preferences.SubtitlesPreferences
import app.gyrolet.mpvrx.preferences.YtdlPreferences
import app.gyrolet.mpvrx.ui.player.PlaybackSession
import app.gyrolet.mpvrx.utils.media.HttpUtils
import app.gyrolet.mpvrx.utils.media.MediaUtils
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.async
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.runInterruptible
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import kotlinx.coroutines.withTimeoutOrNull
import org.json.JSONObject
import java.io.*

data class YtdlpPlaylistEntry(
  val id: String?,
  val url: String,
  val title: String,
  val artist: String?,
  val thumbnailUrl: String?,
  val durationSeconds: Int,
)

data class YtdlpPlaylistMetadata(
  val sourceUrl: String,
  val title: String,
  val entries: List<YtdlpPlaylistEntry>,
)

object YtdlpManager {
  private const val TAG = "YtdlpManager"
  private const val GENERATED_HOOK_CONFIG_MARKER = "# Generated by mpvRx"
  private const val YTDL_DIR = "ytdl"
  private const val PLAYBACK_RUNTIME_VERSION = "1"
  private const val PLAYBACK_RUNTIME_VERSION_FILE = "playback-runtime-version"
  private const val INSTALLATION_INFO_PREFIX = "MPVRX_YTDLP_INFO="
  private const val MAX_IMPORTED_PLAYLIST_ENTRIES = 5_000
  private const val MAX_PLAYLIST_OUTPUT_CHARS = 32L * 1024 * 1024
  private const val PLAYLIST_EXTRACTION_TIMEOUT_MS = 180_000L
  private val installMutex = Mutex()

  private val _installationInfo = MutableStateFlow<YtdlpInstallationInfo?>(null)
  val installationInfo: StateFlow<YtdlpInstallationInfo?> = _installationInfo.asStateFlow()

  @Volatile
  private var runtimeAssetsPrepared = false

  private val installationInfoScript =
    """
    import json, sys
    sys.path.insert(0, sys.argv[1])
    from yt_dlp import version
    fields = {
        "version": getattr(version, "__version__", ""),
        "channel": getattr(version, "CHANNEL", ""),
        "commit": getattr(version, "RELEASE_GIT_HEAD", ""),
        "origin": getattr(version, "ORIGIN", ""),
        "variant": getattr(version, "VARIANT", ""),
    }
    print("$INSTALLATION_INFO_PREFIX" + json.dumps(fields, separators=(",", ":")))
    """.trimIndent()

  // Lua patterns (ytdl_hook `exclude` syntax, `|`-separated) for direct media/manifest
  // paths. The prefix prevents an extension in a query parameter from bypassing yt-dlp;
  // the two suffixes cover plain and tokenized URLs. Loopback hosts are excluded outright:
  // every SMB/FTP/SFTP/WebDAV/torrent stream is served by the app's own local proxy and
  // must never be routed through yt-dlp, extension or not.
  private val DIRECT_MEDIA_EXCLUDE =
    (
      listOf("^127%.0%.0%.1:", "^localhost:") +
        HttpUtils.directMediaExtensions
          .flatMap { extension ->
            listOf(
              "^[^?#]+%.${extension}$",
              "^[^?#]+%.${extension}[?#]",
            )
          }
    ).joinToString("|")

  fun getYtdlDir(context: Context): File = File(context.filesDir, YTDL_DIR).apply { if (!exists()) mkdirs() }

  fun getExecutablePath(context: Context): String =
    File(context.applicationInfo.nativeLibraryDir, "libytdl.so").absolutePath

  suspend fun refreshInstallationInfo(context: Context): YtdlpInstallationInfo =
    withContext(Dispatchers.IO) {
      installMutex.withLock {
        readInstallationInfo(context).also { info -> _installationInfo.value = info }
      }
    }

  fun requiresYtdlp(source: String): Boolean {
    val uri = Uri.parse(source)
    if (!uri.scheme.equals("http", ignoreCase = true) && !uri.scheme.equals("https", ignoreCase = true)) {
      return false
    }

    return !HttpUtils.isDirectMediaUrl(uri)
  }

  fun isPotentialPlaylistUrl(source: String): Boolean {
    val uri = runCatching { Uri.parse(source) }.getOrNull() ?: return false
    if (!uri.scheme.equals("http", true) && !uri.scheme.equals("https", true)) return false
    if (uri.queryParameterNames.any { name ->
        name.lowercase() in setOf("list", "playlist", "playlist_id", "collection", "set") &&
          !uri.getQueryParameter(name).isNullOrBlank()
      }
    ) {
      return true
    }
    return uri.pathSegments.any { segment ->
      segment.lowercase() in setOf("playlist", "playlists", "sets", "album", "albums", "collection", "showcase")
    }
  }

  fun canonicalPlaylistSource(source: String): String {
    val uri = runCatching { Uri.parse(source) }.getOrNull() ?: return source
    val playlistId =
      uri.queryParameterNames
        .firstOrNull { name -> name.equals("list", ignoreCase = true) }
        ?.let(uri::getQueryParameter)
        ?.takeIf(String::isNotBlank)
    if (HttpUtils.isYouTubeUrl(uri) && playlistId != null) {
      return Uri
        .Builder()
        .scheme("https")
        .authority("www.youtube.com")
        .path("playlist")
        .appendQueryParameter("list", playlistId)
        .build()
        .toString()
    }
    return uri.buildUpon().fragment(null).build().toString()
  }

  fun playPlaylist(
    context: Context,
    playlist: YtdlpPlaylistMetadata,
    launchSource: String,
  ) {
    val firstEntry = playlist.entries.firstOrNull() ?: return
    MediaUtils.playFile(
      source = firstEntry.url,
      context = context,
      launchSource = launchSource,
      title = firstEntry.title,
      mediaDescription = playlist.title,
      posterUrl = firstEntry.thumbnailUrl,
      playlist = playlist.entries.map { entry -> Uri.parse(entry.url) },
      playlistIndex = 0,
      playlistTitles = playlist.entries.map { entry -> entry.title },
      playlistArtists = playlist.entries.map { entry -> entry.artist.orEmpty() },
      playlistArtworkUrls = playlist.entries.map { entry -> entry.thumbnailUrl.orEmpty() },
      playlistDurationsSeconds = playlist.entries.map { entry -> entry.durationSeconds },
    )
  }

  suspend fun extractPlaylist(
    context: Context,
    source: String,
    preferences: YtdlPreferences,
    userAgentOverride: String? = null,
    onLog: (String) -> Unit = {},
  ): Result<YtdlpPlaylistMetadata> =
    withContext(Dispatchers.IO) {
      if (!isPotentialPlaylistUrl(source)) {
        return@withContext Result.failure(IllegalArgumentException("The URL does not identify a playlist"))
      }

      try {
        installMutex.withLock {
          if (!prepareRuntimeAssets(context, onLog)) {
            return@withLock Result.failure(IllegalStateException("yt-dlp runtime assets are unavailable"))
          }
          if (!isPlaybackRuntimeReady(context) && !installYtdlp(context, onLog)) {
            return@withLock Result.failure(IllegalStateException("yt-dlp is not installed"))
          }

          val canonicalSource = canonicalPlaylistSource(source)
          val output = StringBuilder()
          val command =
            buildList {
              add(getExecutablePath(context))
              add(File(getYtdlDir(context), "yt-dlp").absolutePath)
              add("--ignore-config")
              add("--flat-playlist")
              add("--dump-single-json")
              add("--yes-playlist")
              add("--skip-download")
              add("--ignore-errors")
              add("--no-warnings")
              add("--no-progress")
              add("--playlist-end")
              add(MAX_IMPORTED_PLAYLIST_ENTRIES.toString())

              (userAgentOverride?.takeIf(String::isNotBlank)
                ?: preferences.customUserAgent.get().takeIf(String::isNotBlank))?.let { userAgent ->
                add("--user-agent")
                add(userAgent)
              }
              preferences.referer.get().takeIf(String::isNotBlank)?.let { referer ->
                add("--referer")
                add(referer)
              }
              preferences.proxy.get().takeIf(String::isNotBlank)?.let { proxy ->
                add("--proxy")
                add(proxy)
              }
              preferences.extractorArgs.get().takeIf(String::isNotBlank)?.let { extractorArgs ->
                add("--extractor-args")
                add(extractorArgs)
              }
              if (preferences.geoBypass.get()) add("--geo-bypass")

              val cookiesFile =
                preferences.cookiesFile.get().takeIf(String::isNotBlank)
                  ?.let(::File)
                  ?.takeIf(File::isFile)
                  ?: AndroidCookieJar.playbackCookieFile(context).takeIf(File::isFile)
              cookiesFile?.let { file ->
                add("--cookies")
                add(file.absolutePath)
              }

              File(context.applicationInfo.nativeLibraryDir, "libqjs.so")
                .takeIf(File::isFile)
                ?.let { quickJs ->
                  add("--js-runtimes")
                  add("quickjs:${quickJs.absolutePath}")
                }
              add("--")
              add(canonicalSource)
            }

          val completed = executePlaylistExtractionProcess(command, context) { chunk -> output.append(chunk) }
          if (!completed) {
            return@withLock Result.failure(IllegalStateException("yt-dlp could not read this playlist"))
          }
          val metadata =
            parsePlaylistMetadata(canonicalSource, output.toString())
              ?: return@withLock Result.failure(IllegalStateException("No playable entries were found"))
          Result.success(metadata)
        }
      } catch (cancellation: CancellationException) {
        throw cancellation
      } catch (error: Exception) {
        Result.failure(error)
      }
    }

  private fun parsePlaylistMetadata(
    source: String,
    output: String,
  ): YtdlpPlaylistMetadata? {
    val payload =
      output
        .lineSequence()
        .map(String::trim)
        .lastOrNull { line -> line.startsWith('{') && line.endsWith('}') }
        ?: return null
    val root = JSONObject(payload)
    val entriesJson = root.optJSONArray("entries") ?: return null
    val sourceIsYouTube = HttpUtils.isYouTubeUrl(Uri.parse(source))
    val entries = ArrayList<YtdlpPlaylistEntry>(entriesJson.length().coerceAtMost(MAX_IMPORTED_PLAYLIST_ENTRIES))
    val seenUrls = HashSet<String>()
    for (index in 0 until minOf(entriesJson.length(), MAX_IMPORTED_PLAYLIST_ENTRIES)) {
      val item = entriesJson.optJSONObject(index) ?: continue
      val id = item.optionalString("id")
      val extractor = item.optionalString("ie_key") ?: item.optionalString("extractor_key")
      val isYouTubeEntry = sourceIsYouTube || extractor?.contains("youtube", ignoreCase = true) == true
      val url =
        if (isYouTubeEntry && id != null) {
          "https://www.youtube.com/watch?v=$id"
        } else {
          sequenceOf("webpage_url", "original_url", "url")
            .mapNotNull { key -> item.optionalString(key) }
            .firstOrNull { candidate ->
              candidate.startsWith("http://", true) || candidate.startsWith("https://", true)
            }
        } ?: continue
      if (!seenUrls.add(url)) continue

      val title =
        sequenceOf("title", "fulltitle", "id")
          .mapNotNull { key -> item.optionalString(key) }
          .firstOrNull()
          ?: "Video ${entries.size + 1}"
      val artist =
        sequenceOf("artist", "creator", "uploader", "channel")
          .mapNotNull { key -> item.optionalString(key) }
          .firstOrNull()
      val thumbnail =
        if (isYouTubeEntry && id != null) {
          "https://i.ytimg.com/vi/$id/hqdefault.jpg"
        } else {
          item.optionalString("thumbnail")
            ?: item.optJSONArray("thumbnails")
              ?.let { thumbnails ->
                (thumbnails.length() - 1 downTo 0)
                  .asSequence()
                  .mapNotNull { thumbnailIndex -> thumbnails.optJSONObject(thumbnailIndex)?.optionalString("url") }
                  .firstOrNull()
              }
        }
      val duration = item.optDouble("duration", -1.0).takeIf { it.isFinite() && it >= 0.0 }?.toInt() ?: -1
      entries +=
        YtdlpPlaylistEntry(
          id = id,
          url = url,
          title = title,
          artist = artist,
          thumbnailUrl = thumbnail,
          durationSeconds = duration,
        )
    }
    if (entries.isEmpty()) return null

    val title =
      sequenceOf("title", "playlist_title", "fulltitle", "id")
        .mapNotNull { key -> root.optionalString(key) }
        .firstOrNull()
        ?: "Online Playlist"
    return YtdlpPlaylistMetadata(sourceUrl = source, title = title, entries = entries)
  }

  suspend fun prepareForPlayback(
    context: Context,
    source: String,
    onLog: (String) -> Unit = {},
  ): Boolean {
    val uri = Uri.parse(source)
    val isWebSource = uri.scheme.equals("http", true) || uri.scheme.equals("https", true)
    if (!isWebSource) return true

    return withContext(Dispatchers.IO) {
      installMutex.withLock {
        if (!prepareRuntimeAssets(context, onLog)) return@withLock false
        if (!requiresYtdlp(source) || isPlaybackRuntimeReady(context)) return@withLock true

        onLog("Preparing the current yt-dlp web playback runtime.\n")
        installYtdlp(context, onLog)
      }
    }
  }

  /** Ensures the yt-dlp runtime is installed regardless of URL shape (used by the downloader). */
  suspend fun ensureRuntimeInstalled(
    context: Context,
    onLog: (String) -> Unit = {},
  ): Boolean =
    withContext(Dispatchers.IO) {
      installMutex.withLock {
        if (!prepareRuntimeAssets(context, onLog)) return@withLock false
        if (isPlaybackRuntimeReady(context)) return@withLock true
        installYtdlp(context, onLog)
      }
    }

  suspend fun copyAssets(context: Context) =
    withContext(Dispatchers.IO) {
      installMutex.withLock {
        runtimeAssetsPrepared = copyRuntimeAssets(context)
      }
    }

  private fun copyRuntimeAssets(context: Context, onLog: (String) -> Unit = {}): Boolean {
    val ytdlDir = getYtdlDir(context)

    // Clean up old potentially problematic scripts from multiple possible locations
    listOf("youtube-dl", "youtube-dl.sh").forEach { name ->
      File(context.filesDir, name).delete()
      File(ytdlDir, name).delete()
    }

    // Files to copy from assets/ytdl/ to filesDir/ytdl/
    val ytdlFiles = arrayOf("setup.py", "python313.zip")
    var copied = true
    for (name in ytdlFiles) {
      copied = copyAssetFile(context, "ytdl/$name", File(ytdlDir, name), onLog) && copied
    }

    // cacert.pem goes to filesDir/
    copied = copyAssetFile(context, "cacert.pem", File(context.filesDir, "cacert.pem"), onLog) && copied

    copyAssetFile(context, "ytdl/wrapper", File(ytdlDir, "wrapper"), onLog)
    // Set executable permission on wrapper (just in case it's used)
    File(ytdlDir, "wrapper").setExecutable(true)
    return copied
  }

  private fun copyAssetFile(
    context: Context,
    assetPath: String,
    outFile: File,
    onLog: (String) -> Unit,
  ): Boolean {
    val temporaryFile = File(outFile.parentFile, "${outFile.name}.tmp")
    return try {
      context.assets.open(assetPath).use { input ->
        FileOutputStream(temporaryFile).use { output ->
          if (input.copyTo(output) == 0L) throw IOException("Bundled asset is empty: $assetPath")
          output.fd.sync()
        }
        if (!temporaryFile.renameTo(outFile)) throw IOException("Could not replace bundled asset: $assetPath")
        Log.d(TAG, "Copied asset: $assetPath")
        true
      }
    } catch (e: IOException) {
      Log.e(TAG, "Failed to copy asset: $assetPath", e)
      onLog("$assetPath: ${e.message}\n")
      false
    } finally {
      temporaryFile.delete()
    }
  }

  fun setupMpvOptions(
    context: Context,
    ytdlPreferences: YtdlPreferences,
    subtitlesPreferences: SubtitlesPreferences,
  ) {
    val nativeLibDir = context.applicationInfo.nativeLibraryDir
    val ytdlBinaryPath = File(nativeLibDir, "libytdl.so").absolutePath
    val ytdlDir = getYtdlDir(context).absolutePath
    val ytDlpScriptPath = File(ytdlDir, "yt-dlp").absolutePath
    val pythonPath = File(nativeLibDir, "libpython.so").absolutePath
    val quickJsPath = File(nativeLibDir, "libqjs.so").absolutePath

    // Set environment variables for the subprocesses started by libmpv
    try {
      Os.setenv("YTDL_PYTHON", pythonPath, true)
      Os.setenv("YTDL_SCRIPT", ytDlpScriptPath, true)
      Os.setenv("PYTHONHOME", ytdlDir, true)
      // Include both the zip and the directory itself in PYTHONPATH
      // Also include nativeLibDir for potential .so modules
      Os.setenv("PYTHONPATH", "$ytdlDir/python313.zip:$ytdlDir:$nativeLibDir", true)
      Os.setenv("SSL_CERT_FILE", File(context.filesDir, "cacert.pem").absolutePath, true)

      // Add nativeLibDir to PATH so scripts can find our bridge if they search PATH
      val currentPath = runCatching { Os.getenv("PATH") }.getOrNull()
      val newPath = if (currentPath.isNullOrBlank()) nativeLibDir else "$nativeLibDir:$currentPath"
      Os.setenv("PATH", newPath, true)

      // Set LD_LIBRARY_PATH for the subprocess to find libpython.so's dependencies
      val currentLd = runCatching { Os.getenv("LD_LIBRARY_PATH") }.getOrNull()
      val newLd = if (currentLd.isNullOrBlank()) nativeLibDir else "$nativeLibDir:$currentLd"
      Os.setenv("LD_LIBRARY_PATH", newLd, true)

      Log.d(TAG, "Environment variables set for ytdl bridge")
    } catch (e: Exception) {
      Log.e(TAG, "Failed to set environment variables", e)
    }

    // Check if yt-dlp actually exists. If not, log a warning.
    val ytDlpFile = File(ytdlDir, "yt-dlp")
    if (!ytDlpFile.exists()) {
      Log.w(TAG, "yt-dlp not found in ${ytDlpFile.absolutePath}. Subprocess will fail until installed.")
    }
    if (!File(quickJsPath).exists()) {
      Log.w(TAG, "QuickJS runtime not found at $quickJsPath. Full YouTube extraction may be unavailable.")
    }

    val storedSettings = YtdlpOptionSettings.fromPreferences(ytdlPreferences, subtitlesPreferences)
    val settings =
      storedSettings.copy(
        cookiesFile =
          storedSettings.cookiesFile.ifBlank {
            AndroidCookieJar.playbackCookieFile(context).absolutePath
          },
        javascriptRuntime = "quickjs:$quickJsPath",
      )
    val resolvedOptions = YtdlpOptionsBuilder.build(settings)
    val ua = ytdlPreferences.customUserAgent.get().ifBlank { YtdlpOptionsBuilder.DEFAULT_USER_AGENT }
    // Keep mpv's delay-loaded all-format path enabled for every audio preference. Disabling it for
    // the default Auto mode was a post-v1.4.1 regression: split video/audio URLs then depended on a
    // single eagerly selected result and some supported sites failed before mpv could choose tracks.
    val allFormats = "yes"

    // Keep a generated fallback for ytdl_hook. This file is app-owned compatibility state, not a
    // user preference: mpv.conf ownership must never delete it or leave a stale bundled path
    // behind. A genuinely hand-written hook file is preserved and the required bootstrap values
    // are supplied independently through app-owned script options below.
    try {
      val scriptOptsDir = File(context.filesDir, "script-opts")
      if (!scriptOptsDir.exists()) scriptOptsDir.mkdirs()
      val ytdlConf = File(scriptOptsDir, "ytdl_hook.conf")
      val existingContent = ytdlConf.takeIf(File::isFile)?.readText().orEmpty()
      val generatedConfig =
        existingContent.startsWith(GENERATED_HOOK_CONFIG_MARKER) ||
          isLegacyGeneratedHookConfig(existingContent)

      when {
        existingContent.isNotBlank() && !generatedConfig -> Log.d(TAG, "Preserving user-supplied ytdl_hook.conf")
        else -> {
          val confLines =
            buildList {
              add(GENERATED_HOOK_CONFIG_MARKER)
              add("ytdl_path=$ytdlBinaryPath")
              add("all_formats=$allFormats")
              add("force_all_formats=yes")
              add("try_ytdl_first=yes")
              add("exclude=$DIRECT_MEDIA_EXCLUDE")
            }
          ytdlConf.writeText(confLines.joinToString("\n", postfix = "\n"))
          Log.d(TAG, "Created generated ytdl_hook.conf at ${ytdlConf.absolutePath}")
        }
      }
    } catch (e: Exception) {
      Log.e(TAG, "Failed to create ytdl_hook.conf", e)
    }

    // Apply options to MPV core
    PlaybackSession.setIntegrationOptionString("ytdl", "yes")
    PlaybackSession.setIntegrationOptionString("ytdl-path", ytdlBinaryPath)

    // These values are part of mpvRx's bundled bridge contract. They intentionally bypass
    // preference ownership so a broad script-opts override cannot remove half of the integration.
    PlaybackSession.setIntegrationOptionString("script-opts-append", "ytdl_hook-path=$ytdlBinaryPath")
    PlaybackSession.setIntegrationOptionString("script-opts-append", "ytdl_hook-ytdl_path=$ytdlBinaryPath")
    PlaybackSession.setIntegrationOptionString("script-opts-append", "ytdl_hook-all_formats=$allFormats")
    PlaybackSession.setIntegrationOptionString("script-opts-append", "ytdl_hook-force_all_formats=yes")
    PlaybackSession.setIntegrationOptionString("script-opts-append", "ytdl_hook-try_ytdl_first=yes")
    // Skip yt-dlp for direct media/manifest URLs (.m3u8/.mpd/.mp4/.ts/...). Without this,
    // ytdl_hook intercepts every http(s) URL and routes it through yt-dlp's generic
    // extractor, which chokes on tokenized HLS/CDN links — so mpv never falls back to
    // ffmpeg's native HLS demuxer and playback fails (while MX Player/VLC play it fine).
    PlaybackSession.setIntegrationOptionString("script-opts-append", "ytdl_hook-exclude=$DIRECT_MEDIA_EXCLUDE")

    // Always derive this from typed preferences so newly added format controls cannot
    // be shadowed by an older cached generated string.
    val ytdlFormat = resolvedOptions.format
    if (ytdlFormat.isNotBlank()) {
      PlaybackSession.setOptionString("ytdl-format", ytdlFormat)
    }

    // Global User-Agent to avoid blocks at the network level
    PlaybackSession.setOptionString("user-agent", ua)

    Log.d(TAG, "Setting ytdl-format to: $ytdlFormat")
    Log.d(TAG, "Setting ytdl-raw-options to: ${resolvedOptions.rawOptions}")
    PlaybackSession.setOptionString("ytdl-raw-options", resolvedOptions.rawOptions)
    PlaybackSession.setIntegrationOptionString("script-opts-append", "ytdl_hook-user_agent=\"$ua\"")

    Log.d(TAG, "MPV ytdl options set. Binary: $ytdlBinaryPath")
  }

  private fun isLegacyGeneratedHookConfig(content: String): Boolean {
    if (content.isBlank()) return false
    val options =
      content
        .lineSequence()
        .map(String::trim)
        .filter { it.isNotEmpty() && !it.startsWith("#") }
        .mapNotNull { line ->
          val separator = line.indexOf('=')
          if (separator <= 0) null else line.take(separator).trim() to line.drop(separator + 1).trim()
        }.toMap()
    return options.keys ==
      setOf("ytdl_path", "all_formats", "force_all_formats", "try_ytdl_first", "exclude") &&
      !options["ytdl_path"].isNullOrBlank() &&
      options["all_formats"] == "yes" &&
      options["force_all_formats"] == "yes" &&
      options["try_ytdl_first"] == "yes" &&
      options["exclude"] == DIRECT_MEDIA_EXCLUDE
  }

  suspend fun runInstall(
    context: Context,
    onLog: (String) -> Unit,
  ): Boolean =
    withContext(Dispatchers.IO) {
      installMutex.withLock {
        if (!prepareRuntimeAssets(context, onLog)) return@withLock false
        installYtdlp(context, onLog)
      }
    }

  suspend fun runUpdate(
    context: Context,
    onLog: (String) -> Unit,
  ): Boolean =
    withContext(Dispatchers.IO) {
      installMutex.withLock {
        if (!prepareRuntimeAssets(context, onLog) || !isInstalled(context)) {
          _installationInfo.value = readInstallationInfo(context)
          return@withLock false
        }

        val ytdlDir = getYtdlDir(context)
        val pythonBinary = getExecutablePath(context)
        val ytDlp = File(ytdlDir, "yt-dlp").absolutePath
        val command = mutableListOf(pythonBinary, ytDlp, "--update")
        val updated = runPythonProcess("Updating yt-dlp...", command, context, onLog)
        if (updated) {
          markPlaybackRuntimeReady(context)
        }
        _installationInfo.value = readInstallationInfo(context)
        updated
      }
    }

  suspend fun runUpdateToNightly(
    context: Context,
    onLog: (String) -> Unit,
  ): Boolean =
    withContext(Dispatchers.IO) {
      installMutex.withLock {
        if (!prepareRuntimeAssets(context, onLog) || !isInstalled(context)) {
          _installationInfo.value = readInstallationInfo(context)
          return@withLock false
        }

        val ytdlDir = getYtdlDir(context)
        val pythonBinary = getExecutablePath(context)
        val ytDlp = File(ytdlDir, "yt-dlp").absolutePath
        val command = mutableListOf(pythonBinary, ytDlp, "--update-to", "nightly")
        val updated = runPythonProcess("Updating to yt-dlp nightly...", command, context, onLog)
        if (updated) {
          markPlaybackRuntimeReady(context)
        }
        _installationInfo.value = readInstallationInfo(context)
        updated
      }
    }

  private suspend fun prepareRuntimeAssets(
    context: Context,
    onLog: (String) -> Unit,
  ): Boolean {
    if (!runtimeAssetsPrepared) {
      runtimeAssetsPrepared = copyRuntimeAssets(context, onLog)
    }
    if (!runtimeAssetsPrepared) onLog("Failed to prepare the bundled yt-dlp runtime assets.\n")
    return runtimeAssetsPrepared
  }

  fun isInstalled(context: Context): Boolean {
    val ytDlp = File(getYtdlDir(context), "yt-dlp")
    return ytDlp.isFile && ytDlp.length() > 0L
  }

  private fun readInstallationInfo(context: Context): YtdlpInstallationInfo {
    if (!isInstalled(context)) return YtdlpInstallationInfo.NotInstalled

    val ytdlFile = File(getYtdlDir(context), "yt-dlp")
    val metadataOutput = StringBuilder()
    val metadataRead =
      executePythonProcess(
        command =
          listOf(
            getExecutablePath(context),
            "-c",
            installationInfoScript,
            ytdlFile.absolutePath,
          ),
        context = context,
      ) { line -> metadataOutput.appendLine(line) }
    if (metadataRead) {
      metadataOutput
        .lineSequence()
        .lastOrNull { line -> line.startsWith(INSTALLATION_INFO_PREFIX) }
        ?.removePrefix(INSTALLATION_INFO_PREFIX)
        ?.let(::parseInstallationInfo)
        ?.let { return it }
    }

    val versionOutput = StringBuilder()
    val versionRead =
      executePythonProcess(
        command = listOf(getExecutablePath(context), ytdlFile.absolutePath, "--version"),
        context = context,
      ) { line -> versionOutput.appendLine(line) }
    val version =
      versionOutput
        .lineSequence()
        .map(String::trim)
        .firstOrNull { line -> line.matches(Regex("""\d+(?:\.\d+)+""")) }
        .takeIf { versionRead }
    return YtdlpInstallationInfo(
      isInstalled = true,
      version = version,
      channel = YtdlpReleaseChannel.resolve(channel = null, origin = null, version = version),
    )
  }

  private fun parseInstallationInfo(payload: String): YtdlpInstallationInfo? =
    runCatching {
      val json = JSONObject(payload)
      val version = json.optionalString("version")
      val channel = json.optionalString("channel")
      val origin = json.optionalString("origin")
      YtdlpInstallationInfo(
        isInstalled = true,
        version = version,
        channel = YtdlpReleaseChannel.resolve(channel, origin, version),
        commitHash = json.optionalString("commit"),
        origin = origin,
        variant = json.optionalString("variant"),
      )
    }.onFailure { error ->
      Log.w(TAG, "Failed to parse installed yt-dlp metadata", error)
    }.getOrNull()

  private fun JSONObject.optionalString(key: String): String? =
    optString(key)
      .trim()
      .takeIf { value -> value.isNotEmpty() && !value.equals("null", ignoreCase = true) }

  private fun isPlaybackRuntimeReady(context: Context): Boolean =
    isInstalled(context) &&
      File(getYtdlDir(context), PLAYBACK_RUNTIME_VERSION_FILE).readTextOrNull() == PLAYBACK_RUNTIME_VERSION

  private fun markPlaybackRuntimeReady(context: Context) {
    runCatching {
      File(getYtdlDir(context), PLAYBACK_RUNTIME_VERSION_FILE).writeText(PLAYBACK_RUNTIME_VERSION)
    }.onFailure { error ->
      Log.w(TAG, "Failed to persist yt-dlp playback runtime version", error)
    }
  }

  private fun File.readTextOrNull(): String? =
    runCatching { takeIf(File::isFile)?.readText()?.trim() }.getOrNull()

  private fun installYtdlp(
    context: Context,
    onLog: (String) -> Unit,
  ): Boolean {
    val ytdlDir = getYtdlDir(context)
    val nativeLibDir = context.applicationInfo.nativeLibraryDir
    val pythonBinary = getExecutablePath(context)
    val setupPy = File(ytdlDir, "setup.py").absolutePath
    val command = mutableListOf(pythonBinary, setupPy, nativeLibDir)
    val installed = runPythonProcess("Installing yt-dlp...", command, context, onLog) && isInstalled(context)
    if (installed) markPlaybackRuntimeReady(context)
    _installationInfo.value = readInstallationInfo(context)
    return installed
  }

  private fun runPythonProcess(
    title: String,
    command: List<String>,
    context: Context,
    onLog: (String) -> Unit,
  ): Boolean {
    onLog("$title\n")
    return executePythonProcess(command, context) { line -> onLog("$line\n") }
  }

  private fun executePythonProcess(
    command: List<String>,
    context: Context,
    onOutput: (String) -> Unit,
  ): Boolean {
    return try {
      val process = startPythonProcess(command, context)

      BufferedReader(InputStreamReader(process.inputStream)).use { reader ->
        reader.lineSequence().forEach(onOutput)
      }
      process.waitFor() == 0
    } catch (e: Exception) {
      onOutput("Error: ${e.message}")
      false
    }
  }

  private suspend fun executePlaylistExtractionProcess(
    command: List<String>,
    context: Context,
    onOutput: (String) -> Unit,
  ): Boolean =
    coroutineScope {
      val process = startPythonProcess(command, context)
      val outputJob =
        async(Dispatchers.IO) {
          var outputChars = 0L
          InputStreamReader(process.inputStream).use { reader ->
            val buffer = CharArray(DEFAULT_BUFFER_SIZE)
            while (true) {
              val count = reader.read(buffer)
              if (count < 0) break
              outputChars += count
              check(outputChars <= MAX_PLAYLIST_OUTPUT_CHARS) { "Playlist metadata is too large" }
              onOutput(String(buffer, 0, count))
            }
          }
        }
      val exitJob = async(Dispatchers.IO) { runInterruptible { process.waitFor() } }

      try {
        withTimeoutOrNull(PLAYLIST_EXTRACTION_TIMEOUT_MS) {
          val exitCode = exitJob.await()
          outputJob.await()
          exitCode == 0
        } ?: throw IllegalStateException("Playlist import timed out")
      } finally {
        if (process.isAlive) process.destroyForcibly()
        runCatching { process.inputStream.close() }
        outputJob.cancel()
        exitJob.cancel()
      }
    }

  internal fun startPythonProcess(
    command: List<String>,
    context: Context,
  ): Process {
    val processBuilder =
      ProcessBuilder(command)
        .directory(getYtdlDir(context))
        .redirectErrorStream(true)
    val env = processBuilder.environment()
    val ytdlDir = getYtdlDir(context).absolutePath
    val nativeLibDir = context.applicationInfo.nativeLibraryDir

    // Clear YTDL_SCRIPT so the bridge doesn't try to wrap yt-dlp during setup/update.
    env.remove("YTDL_SCRIPT")
    env["YTDL_PYTHON"] = File(nativeLibDir, "libpython.so").absolutePath
    env["PYTHONHOME"] = ytdlDir
    env["PYTHONPATH"] = "$ytdlDir/python313.zip:$ytdlDir:$nativeLibDir"
    env["HOME"] = context.filesDir.absolutePath
    env["XDG_CACHE_HOME"] = context.cacheDir.absolutePath
    env["TMPDIR"] = context.cacheDir.absolutePath
    env["SSL_CERT_FILE"] = File(context.filesDir, "cacert.pem").absolutePath
    env["LD_LIBRARY_PATH"] = nativeLibDir
    return processBuilder.start()
  }
}
