[versions]
agp = "9.4.1"
commonsNet = "3.13.0"
smbj = "0.15.0"
jsch = "2.28.7"
kotlin = "2.4.20"
ksp = "2.3.12"
composeBom = "2026.09.00"
activityCompose = "1.13.0"
koin = "4.2.2"
lazycolumnscrollbar = "2.2.0"
nanohttpd = "2.3.1"
room = "2.8.5"
navigation3 = "1.1.7"
lifecycle = "2.10.0"
kotlinx-serialization = "1.11.0"
kotlinx-collections-immutable = "0.5.2"
profileinstaller = "1.4.1"

truetype-parser = "2.1.4"
accompanist = "0.37.3"
okhttp = "5.5.0"
jsoup = "1.23.2"
sardineAndroid = "0.9"
reorderable = "3.1.0"
googleMaterial = "1.14.0"
androidxCore = "1.19.1"
androidxPreference = "1.2.1"
androidxConstraintLayout = "2.2.2"
media3 = "1.11.1"
soraEditor = "0.24.6"
androidxMaterial3 = "1.5.0-alpha28"
androidxAppcompat = "1.8.0"
composeConstraintLayout = "1.1.2"
androidxMedia = "1.8.0"
androidxDocumentfile = "1.1.0"
androidxPalette = "1.0.0"
composePrefs = "2.2.0"
desugarJdkLibs = "2.1.5"
fsaf = "1.1.3"
materialSymbols = "2.2.1"
seeker = "2.0.1"
markdownRenderer = "0.45.0"
kotlinTest = "2.4.20"
mediainfo = "v1.0.0-fix"
mpvlib = "1.0.9"
googleCast = "22.3.1"
androidxBiometric = "1.4.0-alpha07"
leakcanary = "2.14"
crashx = "7.0.1"
kmpVibrate = "1.1.0"
libtorrent4j = "2.1.0-39"
libarchiveAndroid = "1.1.7"
ktlint = "14.2.0"
telephoto = "0.19.0"

[libraries]
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
commons-net = { module = "commons-net:commons-net", version.ref = "commonsNet" }
smbj = { module = "com.hierynomus:smbj", version.ref = "smbj" }
jsch = { module = "com.github.mwiede:jsch", version.ref = "jsch" }
lazycolumnscrollbar = { module = "com.github.nanihadesuka:LazyColumnScrollbar", version.ref = "lazycolumnscrollbar" }
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd" }
sardine-android = { module = "com.github.thegrizzlylabs:sardine-android", version.ref = "sardineAndroid" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxMaterial3" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
composables-material-symbols-rounded-filled-android = { module = "com.composables:icons-material-symbols-rounded-filled-android", version.ref = "materialSymbols" }
composables-material-symbols-rounded-filled-cmp = { module = "com.composables:icons-material-symbols-rounded-filled-cmp-jvm", version.ref = "materialSymbols" }
androidx-compose-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "composeConstraintLayout" }
androidx-compose-animation-graphics = { group = "androidx.compose.animation", name = "animation-graphics-android" }
mediasession = { group = "androidx.media", name = "media", version.ref = "androidxMedia" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation3" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "androidxDocumentfile" }
androidx-palette = { group = "androidx.palette", name = "palette-ktx", version.ref = "androidxPalette" }
seeker = { module = "com.github.abdallahmehiz:seeker", version.ref = "seeker" }
markdown-renderer-m3 = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "markdownRenderer" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlinTest" }
mediainfo-lib = { module = "com.github.marlboro-advance:mediainfoAndroid", version.ref = "mediainfo" }
mpvlib-standard = { module = "app.gyrolet.mpvlib:mpvlib", version.ref = "mpvlib" }
mpvlib-no-vulkan = { module = "app.gyrolet.mpvlib:mpvlib-no-vulkan", version.ref = "mpvlib" }
mpvlib-fongmi = { module = "app.gyrolet.mpvlib:mpvlib-fongmi", version.ref = "mpvlib" }

google-material = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidxPreference" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintLayout" }
androidx-media3-common = { module = "androidx.media3:media3-common", version.ref = "media3" }
androidx-media3-effect = { module = "androidx.media3:media3-effect", version.ref = "media3" }
androidx-media3-transformer = { module = "androidx.media3:media3-transformer", version.ref = "media3" }
sora-editor-bom = { module = "io.github.rosemoe:editor-bom", version.ref = "soraEditor" }
sora-editor = { module = "io.github.rosemoe:editor" }
sora-language-textmate = { module = "io.github.rosemoe:language-textmate" }
# sora-oniguruma-native = { module = "io.github.rosemoe:oniguruma-native" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }

compose-prefs = { module = "me.zhanghai.compose.preference:preference", version.ref = "composePrefs" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

kotlinx-immutable-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

truetype-parser = { module = "io.github.yubyf:truetypeparser-light", version.ref = "truetype-parser" }
fsaf = { module = "com.github.K1rakishou:Fuck-Storage-Access-Framework", version.ref = "fsaf" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
google-cast-framework = { module = "com.google.android.gms:play-services-cast-framework", version.ref = "googleCast" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "androidxBiometric" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
crashx = { module = "io.github.tutorialsandroid:crashx", version.ref = "crashx" }
kmp-vibrate = { module = "io.github.jmseb3:vibrate", version.ref = "kmpVibrate" }
libtorrent4j = { module = "org.libtorrent4j:libtorrent4j", version.ref = "libtorrent4j" }
libtorrent4j-android-arm64 = { module = "org.libtorrent4j:libtorrent4j-android-arm64", version.ref = "libtorrent4j" }
libtorrent4j-android-arm = { module = "org.libtorrent4j:libtorrent4j-android-arm", version.ref = "libtorrent4j" }
libtorrent4j-android-x86 = { module = "org.libtorrent4j:libtorrent4j-android-x86", version.ref = "libtorrent4j" }
libtorrent4j-android-x8664 = { module = "org.libtorrent4j:libtorrent4j-android-x86_64", version.ref = "libtorrent4j" }
libarchive-android = { module = "me.zhanghai.android.libarchive:library", version.ref = "libarchiveAndroid" }
telephoto-zoomable = { module = "me.saket.telephoto:zoomable", version.ref = "telephoto" }

[bundles]
koin = ["koin-core", "koin-android", "koin-compose", "koin-viewmodel"]
compose-navigation3 = ["androidx-navigation3-runtime", "androidx-navigation3-ui", "androidx-lifecycle-runtime-compose"]

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "room" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
